"""add watchlist_config table

Revision ID: e37df11b4061
Revises: xxxx_add_watchlist_tables
Create Date: 2026-03-30 14:29:17.898741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37df11b4061'
down_revision: Union[str, Sequence[str], None] = 'xxxx_add_watchlist_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_config_key', 'watchlist_config', ['config_key'], unique=False)
    op.create_index(op.f('ix_watchlist_config_config_key'), 'watchlist_config', ['config_key'], unique=True)
    op.drop_index(op.f('idx_analysis_batches_created_at'), table_name='analysis_batches')
    op.drop_index(op.f('idx_analysis_batches_status'), table_name='analysis_batches')
    op.create_index(op.f('ix_analysis_batches_created_at'), 'analysis_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_batches_status'), 'analysis_batches', ['status'], unique=False)
    op.drop_index(op.f('idx_analysis_tasks_created_at'), table_name='analysis_tasks')
    op.drop_index(op.f('idx_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_index(op.f('idx_analysis_tasks_symbol'), table_name='analysis_tasks')
    op.create_index(op.f('ix_analysis_tasks_created_at'), 'analysis_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_symbol'), 'analysis_tasks', ['symbol'], unique=False)
    op.drop_constraint(op.f('watchlist_symbol_key'), 'watchlist', type_='unique')
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.create_unique_constraint(op.f('watchlist_symbol_key'), 'watchlist', ['symbol'])
    op.drop_index(op.f('ix_analysis_tasks_symbol'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_created_at'), table_name='analysis_tasks')
    op.create_index(op.f('idx_analysis_tasks_symbol'), 'analysis_tasks', ['symbol'], unique=False)
    op.create_index(op.f('idx_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_analysis_tasks_created_at'), 'analysis_tasks', ['created_at'], unique=False)
    op.drop_index(op.f('ix_analysis_batches_status'), table_name='analysis_batches')
    op.drop_index(op.f('ix_analysis_batches_created_at'), table_name='analysis_batches')
    op.create_index(op.f('idx_analysis_batches_status'), 'analysis_batches', ['status'], unique=False)
    op.create_index(op.f('idx_analysis_batches_created_at'), 'analysis_batches', ['created_at'], unique=False)
    op.drop_index(op.f('ix_watchlist_config_config_key'), table_name='watchlist_config')
    op.drop_index('idx_watchlist_config_key', table_name='watchlist_config')
    op.drop_table('watchlist_config')
    # ### end Alembic commands ###
